### PR TITLE
Added select-buttons to lists

### PR DESCRIPTION
**Pull request by dpuscher**
Works on watchlist and bookmark-lists

### CODE REVIEW

**Comment by lukeIam** [comment]
Hi @dpuscher,

thanks for your contribution to GClh !

I'll have a look an your change.

**Comment by lukeIam** [comment]
I like your feature and I think that it should be included in the next version.

But I might found a litte bug: visit http://www.geocaching.com/bookmarks/view.aspx?guid=1fc44d4f-055d-49f7-9f91-2863946440b4

Click "All" -> "None" -> "All"

**Comment by dpuscher** [comment]
I can't find any problems using the feature on the given order on this bookmark-list. What kind of bug do you encounter?

**Comment by lukeIam** [comment]
It seems that the problem only occurs with chrome:
After clicking on "None" neither "All" nor "Invert" is working anymore.

With firefox everything looks good.

**Comment by Torsten-** [comment]
Thanks for the new feature! I've merged lukes branch because it has the fixes - so I'll close this push request.
The feature will be included in the next relase.

**Pull request closed without merging**
